// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zquqkslmmibfgartyqhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxdXFrc2xtbWliZmdhcnR5cWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjU5NzQsImV4cCI6MjA2ODc0MTk3NH0.7ws0fp_zXh3VjQmSgKGsE4WWj3kvlEfTkZL4B9xCTO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});